language: php

php: 5.5

# php:
#   - 5.4
#   - 5.5
#   - 5.6

sudo: required
# sudo: false

cache:
  directories:
    - vendor
    - $HOME/.composer/cache

env:
  matrix:
    - PHALCON_VERSION="2.0.1"

addons:
  apt:
    packages:
      - libyaml-dev
      - php5-dev
      - php5-fpm

before_install:
  - cd $TRAVIS_BUILD_DIR
  - pecl channel-update pecl.php.net
  - php -m

install:
  - composer self-update
  - git clone -q --depth=1 https://github.com/phalcon/cphalcon.git -b phalcon-v${PHALCON_VERSION}
  - (cd cphalcon/ext; export CFLAGS="-g3 -O1 -fno-delete-null-pointer-checks -Wall"; phpize &> /dev/null && ./configure --silent --enable-phalcon &> /dev/null && make --silent -j4 > /dev/null && make --silent install && phpenv config-add ../unit-tests/ci/phalcon.ini &> /dev/null)
  - php -r 'echo \Phalcon\Version::get()."\n";'
  - travis_retry composer install --prefer-source --no-interaction

script:
  - phpunit --bootstrap ./tests/phpUnitBootstrap.php tests/

matrix:
  include:
    - os: linux
