language: php

php:
  - 5.5

# env:
#   - DB=mysql

# cache:
#   directories:
#     - $TRAVIS_BUILD_DIR/vendor

install:
  - composer install

script:
  - phpunit --bootstrap ./tests/phpUnitBootstrap.php tests/

matrix:
  include:
    - os: linux
