language: php

cache:
  directories:
    - $TRAVIS_BUILD_DIR/vendor

addons:
  apt:
    packages:
    - php5-common
    - php5-cli

before_install:
  - ./travis/deps.sh

script:
  - php ./composer.phar install
  - ./vendor/bin/phpunit --bootstrap ./tests/phpUnitBootstrap.php tests/

matrix:
  include:
    - os: linux
