language: php

php:
  - 5.4
  - 5.5
  - 5.6

env:
  - DB=mysql

cache:
  directories:
    - $TRAVIS_BUILD_DIR/vendor

install:
  - composer install

script:
  - cd $TRAVIS_BUILD_DIR
  - phpunit --bootstrap ./tests/phpUnitBootstrap.php tests/

matrix:
  include:
    - os: linux
