SET FOREIGN_KEY_CHECKS = 0;
DROP TABLE IF EXISTS accounts;
SET FOREIGN_KEY_CHECKS = 1;

CREATE TABLE accounts (
  id INT(11) UNSIGNED NOT NULL AUTO_INCREMENT,
  identifier VARCHAR(50) NOT NULL,
  created TIMESTAMP NULL,
  modified TIMESTAMP NULL,

  first_name VARCHAR(255) NULL,
  last_name VARCHAR(255) NULL,
  email VARCHAR(255) NULL,

  PRIMARY KEY (id)
);
